import type { Experience } from "./types";

export const interests = [
  "Cars",
  "Design",
  "Music",
  "Startups",
  "Architecture",
  "Cooking",
  "Robotics",
  "Photography",
  "Hiking",
  "Ceramics",
  "Books",
  "Fashion",
  "Travel",
  "Coffee",
  "Film",
  "Woodworking",
  "Volunteering",
  "Museums",
];

export const feelings = [
  "Curious",
  "Creative",
  "Connected",
  "Challenged",
  "Inspired",
  "Adventurous",
  "Peaceful",
  "Useful",
  "Grounded",
];

export const goals = [
  "New friends",
  "Learning",
  "Creativity",
  "Community",
  "Adventure",
  "Craftsmanship",
  "Culture",
  "Better routines",
  "A deeper city life",
];

export const experiences: Experience[] = [
  {
    id: "exp-001",
    slug: "saturday-morning-architecture-walk",
    title: "Saturday Morning Architecture Walk",
    description: "A slow walk through hidden courtyards, adaptive reuse projects, and overlooked building details.",
    longDescription:
      "This walk is built for people who want to see their city differently. A local architect leads a small group through quiet streets, old industrial blocks, and buildings most people pass without noticing. The goal is not to memorize history. The goal is to build the habit of looking closely.",
    date: "Saturday, July 18",
    time: "9:30 AM",
    city: "San Francisco",
    location: "Jackson Square",
    host: "Field Notes Architecture Club",
    cost: "$18",
    category: "Architecture",
    tags: ["walking", "history", "design", "city"],
    vibe: "Observant, quiet, conversational",
    beginnerFriendly: true,
    socialIntensity: "moderate",
    cadence: "Recurring",
    recommendationKind: "Growth",
    whyRecommended: "You care about design and cities. This turns passive interest into a new way of noticing your surroundings.",
    community: "Architecture Walks",
    proofMethod: "Physical QR card at the final courtyard",
    anonymousGuests: [
      {
        code: "Attendee A",
        currentlyExploring: ["Architecture", "Photography", "Coffee Shops"],
        recentPath: ["Museums", "Galleries", "Architecture"],
        attendingBecause: "wants to see the city differently",
      },
      {
        code: "Attendee B",
        currentlyExploring: ["Industrial Design", "Woodworking"],
        recentPath: ["Cars & Coffee", "Sketching", "Industrial Design"],
        attendingBecause: "is tracing how objects become spaces",
      },
    ],
  },
  {
    id: "exp-002",
    slug: "beginner-wheel-throwing-night",
    title: "Beginner Wheel Throwing Night",
    description: "A two-hour ceramics session for people who want to make something with their hands.",
    longDescription:
      "A calm studio night with instruction, clay, tools, and enough structure to get started without feeling watched. You will leave with a small piece, but the real point is the physical reset: hands in material, phone away, shared concentration.",
    date: "Thursday, July 23",
    time: "7:00 PM",
    city: "Oakland",
    location: "Temescal Clay Studio",
    host: "Temescal Clay Studio",
    cost: "$42",
    category: "Ceramics",
    tags: ["craft", "hands-on", "studio", "beginner"],
    vibe: "Tactile, focused, warm",
    beginnerFriendly: true,
    socialIntensity: "quiet",
    cadence: "Recurring",
    recommendationKind: "Surprise",
    whyRecommended: "You asked for creativity and peace. Ceramics is a low-pressure way to enter both.",
    community: "Clay Studio Regulars",
    proofMethod: "Studio stamp after glazing selection",
    anonymousGuests: [
      {
        code: "Attendee A",
        currentlyExploring: ["Pottery", "Craft", "Quiet Creativity"],
        recentPath: ["Coffee Shops", "Museums", "Pottery"],
        attendingBecause: "wants a non-screen creative ritual",
      },
      {
        code: "Attendee B",
        currentlyExploring: ["Architecture", "Woodworking", "Design"],
        recentPath: ["Sketching", "Pottery", "Woodworking"],
        attendingBecause: "is learning material sensitivity",
      },
    ],
  },
  {
    id: "exp-003",
    slug: "maker-space-open-build",
    title: "Makerspace Open Build",
    description: "Open shop hours for 3D printing, electronics benches, laser cutting, and unfinished ideas.",
    longDescription:
      "Bring a project, a question, or nothing at all. The room is full of people debugging prints, repairing old tools, testing sensors, and explaining what they are making. It is a good place to find a collaborator before you know what you want to collaborate on.",
    date: "Tuesday, July 21",
    time: "6:30 PM",
    city: "Berkeley",
    location: "East Bay Fabrication Lab",
    host: "East Bay Fabrication Lab",
    cost: "Free",
    category: "Makerspace",
    tags: ["robotics", "hardware", "3D printing", "electronics"],
    vibe: "Useful, curious, slightly chaotic",
    beginnerFriendly: true,
    socialIntensity: "social",
    cadence: "Recurring",
    recommendationKind: "Passion",
    whyRecommended: "You already like robotics and startups. This is where those interests become physical prototypes.",
    community: "East Bay Makers",
    proofMethod: "NFC tap at the tool desk",
    anonymousGuests: [
      {
        code: "Attendee A",
        currentlyExploring: ["Maker Spaces", "Robotics", "Startup Events"],
        recentPath: ["Startup Events", "Maker Spaces", "Industrial Design"],
        attendingBecause: "is looking for builders outside software",
      },
      {
        code: "Attendee B",
        currentlyExploring: ["3D Printing", "Woodworking", "Cars"],
        recentPath: ["Cars & Coffee", "Sketching", "Maker Spaces"],
        attendingBecause: "wants to turn taste into prototypes",
      },
    ],
  },
  {
    id: "exp-004",
    slug: "coffee-cupping-and-roast-notes",
    title: "Coffee Cupping & Roast Notes",
    description: "Taste five coffees side-by-side and learn how roasters think about origin, processing, and flavor.",
    longDescription:
      "A small table, five cups, and a guided vocabulary for what you are tasting. This is for people who like coffee shops but want to understand what is inside the ritual.",
    date: "Sunday, July 26",
    time: "10:00 AM",
    city: "Los Angeles",
    location: "Arts District Roastery",
    host: "North Window Coffee",
    cost: "$25",
    category: "Coffee",
    tags: ["coffee", "taste", "learning", "craft"],
    vibe: "Sensory, calm, precise",
    beginnerFriendly: true,
    socialIntensity: "moderate",
    cadence: "One-Time",
    recommendationKind: "Growth",
    whyRecommended: "You enjoy places with craft. This deepens a daily habit into a new language.",
    community: "Roast Notes Club",
    proofMethod: "Roaster passphrase printed on the tasting card",
    anonymousGuests: [
      {
        code: "Attendee A",
        currentlyExploring: ["Coffee Shops", "Bookstores", "Startup Events"],
        recentPath: ["Coffee Shops", "Bookstores", "Founder Communities"],
        attendingBecause: "wants a better third-place routine",
      },
    ],
  },
  {
    id: "exp-005",
    slug: "sunset-film-photo-walk",
    title: "Sunset Film Photo Walk",
    description: "A golden-hour photo walk for film and digital photographers who want to practice seeing.",
    longDescription:
      "No portfolio review. No pressure. Just a route, a few prompts, and a group of people trying to notice light before it disappears.",
    date: "Friday, July 17",
    time: "6:45 PM",
    city: "New York",
    location: "DUMBO Waterfront",
    host: "Slow Shutter Society",
    cost: "$12",
    category: "Photography",
    tags: ["photo", "film", "walk", "visual"],
    vibe: "Quietly social, visual, exploratory",
    beginnerFriendly: true,
    socialIntensity: "moderate",
    cadence: "Recurring",
    recommendationKind: "Passion",
    whyRecommended: "You want more creativity and city exploration. This combines both without making it performative.",
    community: "Slow Shutter Society",
    proofMethod: "Group check-in at the final photo stop",
    anonymousGuests: [
      {
        code: "Attendee A",
        currentlyExploring: ["Photography", "Architecture", "Travel"],
        recentPath: ["Coffee Shops", "Photography", "Architecture"],
        attendingBecause: "wants to practice noticing",
      },
    ],
  },
  {
    id: "exp-006",
    slug: "fermentation-for-beginners",
    title: "Fermentation for Beginners",
    description: "Learn kimchi, kraut, and the science of preserving food with a neighborhood cooking school.",
    longDescription:
      "A practical workshop on salt, time, microbes, and confidence. You will make something to take home and learn why fermentation connects cooking, culture, health, and travel.",
    date: "Wednesday, July 29",
    time: "6:00 PM",
    city: "Chicago",
    location: "Logan Square Kitchen",
    host: "Neighborhood Table",
    cost: "$55",
    category: "Cooking",
    tags: ["cooking", "culture", "food", "hands-on"],
    vibe: "Warm, useful, communal",
    beginnerFriendly: true,
    socialIntensity: "social",
    cadence: "One-Time",
    recommendationKind: "Surprise",
    whyRecommended: "You like culture and craft. Fermentation is a doorway into both that most people never search for.",
    community: "Neighborhood Table",
    proofMethod: "Host confirmation after jar labeling",
    anonymousGuests: [
      {
        code: "Attendee A",
        currentlyExploring: ["Cooking", "Culture", "Travel"],
        recentPath: ["Cooking Classes", "Fermentation", "Culture"],
        attendingBecause: "wants culture through practice",
      },
    ],
  },
  {
    id: "exp-007",
    slug: "early-run-bookstore-loop",
    title: "Early Run & Bookstore Loop",
    description: "A gentle three-mile run ending with coffee and a rotating table of books people are carrying.",
    longDescription:
      "This is not a race club. It is a ritual: move through the city, cool down together, then trade book recommendations with people you would not have otherwise met.",
    date: "Saturday, August 1",
    time: "8:00 AM",
    city: "Boston",
    location: "Beacon Hill Books",
    host: "Paperback Miles",
    cost: "Free",
    category: "Running",
    tags: ["running", "books", "coffee", "community"],
    vibe: "Gentle, friendly, ritualistic",
    beginnerFriendly: true,
    socialIntensity: "social",
    cadence: "Recurring",
    recommendationKind: "Growth",
    whyRecommended: "You asked for community and better routines. This makes both easier to start.",
    community: "Paperback Miles",
    proofMethod: "QR code at bookstore coffee table",
    anonymousGuests: [
      {
        code: "Attendee A",
        currentlyExploring: ["Running Clubs", "Bookstores", "Human Connection"],
        recentPath: ["Running Clubs", "Coffee Shops", "Bookstores"],
        attendingBecause: "is new to the city and building routine",
      },
      {
        code: "Attendee B",
        currentlyExploring: ["Books", "Fitness", "Volunteering"],
        recentPath: ["Bookstores", "Running Clubs", "Volunteering"],
        attendingBecause: "wants friendships through repetition",
      },
    ],
  },
  {
    id: "exp-008",
    slug: "industrial-design-sketch-session",
    title: "Industrial Design Sketch Session",
    description: "A low-stakes sketch night for cars, furniture, products, and forms that belong in the real world.",
    longDescription:
      "Bring a notebook. The session starts with quick prompts, moves into object studies, and ends with people sharing methods rather than polished work. It is for people who want to draw ideas into existence.",
    date: "Monday, July 20",
    time: "7:30 PM",
    city: "San Francisco",
    location: "Mission Design Co-op",
    host: "Object Study",
    cost: "$10",
    category: "Design",
    tags: ["cars", "industrial design", "sketching", "products"],
    vibe: "Focused, ambitious, generous",
    beginnerFriendly: true,
    socialIntensity: "moderate",
    cadence: "Recurring",
    recommendationKind: "Passion",
    whyRecommended: "Cars can lead to sketching, sketching to product design, and product design to a new creative path.",
    community: "Object Study",
    proofMethod: "Physical sketch card scanned after critique",
    anonymousGuests: [
      {
        code: "Attendee A",
        currentlyExploring: ["Cars & Coffee", "Automotive Design", "Sketching"],
        recentPath: ["Cars & Coffee", "Automotive Design", "Industrial Design"],
        attendingBecause: "wants to turn car taste into design skill",
      },
      {
        code: "Attendee B",
        currentlyExploring: ["Architecture", "Woodworking", "Industrial Design"],
        recentPath: ["Pottery", "Woodworking", "Architecture"],
        attendingBecause: "is moving from objects to spaces",
      },
    ],
  },
];

export function getWeeklyRecommendations() {
  return [
    experiences.find((experience) => experience.recommendationKind === "Passion")!,
    experiences.find((experience) => experience.recommendationKind === "Growth")!,
    experiences.find((experience) => experience.recommendationKind === "Surprise")!,
  ];
}

export function getExperience(slug: string) {
  return experiences.find((experience) => experience.slug === slug);
}

export function getRelatedExperiences(experience: Experience) {
  return experiences
    .filter((candidate) => candidate.slug !== experience.slug)
    .filter(
      (candidate) =>
        candidate.category === experience.category ||
        candidate.tags.some((tag) => experience.tags.includes(tag)) ||
        candidate.city === experience.city,
    )
    .slice(0, 3);
}
