import type { Experience, Host, User, Transaction, Booking, SeedUser, Post, Connection } from '@serendipity-hq/design'

export const HOSTS: Host[] = [
  {
    id: 'h1',
    name: 'Marta Kovács',
    bio: 'Ceramicist and founder of the Slow Hands studio. Marta has been throwing pots for fifteen years and believes that clay is a form of therapy.',
    venue: 'Slow Hands Studio, Williamsburg',
    avatarSeed: '101',
  },
  {
    id: 'h2',
    name: 'James Okafor',
    bio: 'Sommelier and wine educator. James spent a decade in Burgundy before returning to New York to share what he learned about land, time, and patience.',
    venue: 'The Cork Room, West Village',
    avatarSeed: '102',
  },
  {
    id: 'h3',
    name: 'Suki Tanaka',
    bio: 'Philosopher, former professor, and author of "The Examined Life." Suki runs intimate Socratic seminars for curious non-academics.',
    venue: 'Open Hearth Loft, Brooklyn',
    avatarSeed: '103',
  },
  {
    id: 'h4',
    name: 'Caleb Frost',
    bio: 'Climber and outdoor educator. Caleb has summited peaks on five continents and believes that vertical movement changes how you think.',
    venue: 'Summit Collective Gym, LIC',
    avatarSeed: '104',
  },
  {
    id: 'h5',
    name: 'Nina Reyes',
    bio: 'Chef and forager. Nina blends her Mexican grandmother\'s recipes with hyper-local ingredients gathered from the Hudson Valley.',
    venue: 'Nina\'s Kitchen, Park Slope',
    avatarSeed: '105',
  },
  {
    id: 'h6',
    name: 'Eli Rosen',
    bio: 'Astrophysicist by training, storyteller by calling. Eli runs rooftop stargazing sessions that turn the cosmos into something personal.',
    venue: 'Rooftop at The Wythe, Williamsburg',
    avatarSeed: '106',
  },
]

export const EXPERIENCES: Experience[] = [
  {
    id: 'e1',
    title: 'Introduction to Wheel Throwing',
    lane: 'passion',
    hostId: 'h1',
    description:
      'Spend two hours getting your hands in clay for the first time — or returning to it after too long away. Marta guides small groups through the fundamentals of centering, opening, and pulling walls. You\'ll leave with one piece to be fired and mailed to you, and the memory of making something with your hands.',
    location: 'Slow Hands Studio, 78 N 6th St, Williamsburg',
    dateTime: '2026-07-19T14:00:00',
    price: 85,
    spotsTotal: 8,
    spotsBooked: 5,
    imageSeed: '201',
    tags: ['Pottery', 'Craft', 'Hands-on'],
  },
  {
    id: 'e2',
    title: 'The Language of Burgundy',
    lane: 'passion',
    hostId: 'h2',
    description:
      'A tasting of six wines from the Côte d\'Or, led by James Okafor. This isn\'t a tour of labels — it\'s a lesson in how soil, slope, and season speak through glass. James will walk you through sensory vocabulary you\'ll use for the rest of your life.',
    location: 'The Cork Room, 14 Bank St, West Village',
    dateTime: '2026-07-25T19:00:00',
    price: 120,
    spotsTotal: 10,
    spotsBooked: 7,
    imageSeed: '202',
    tags: ['Wine', 'Tasting', 'Education'],
  },
  {
    id: 'e3',
    title: 'Advanced Throwing: Trimming & Handles',
    lane: 'passion',
    hostId: 'h1',
    description:
      'For those who\'ve thrown before. We\'ll spend the session on trimming technique and attaching handles — the skills that turn a pot into a mug you\'re proud to use every morning.',
    location: 'Slow Hands Studio, 78 N 6th St, Williamsburg',
    dateTime: '2026-08-02T11:00:00',
    price: 95,
    spotsTotal: 6,
    spotsBooked: 2,
    imageSeed: '203',
    tags: ['Pottery', 'Advanced', 'Craft'],
  },
  {
    id: 'e4',
    title: 'The Examined Life: A Socratic Seminar',
    lane: 'growth',
    hostId: 'h3',
    description:
      'What do you actually believe, and why? Suki Tanaka leads a facilitated philosophical discussion on identity, meaning, and the good life. No academic background required — only a willingness to question and be questioned. Six people, two hours, no PowerPoints.',
    location: 'Open Hearth Loft, 320 Atlantic Ave, Brooklyn',
    dateTime: '2026-07-18T18:30:00',
    price: 65,
    spotsTotal: 6,
    spotsBooked: 4,
    imageSeed: '204',
    tags: ['Philosophy', 'Discussion', 'Ideas'],
  },
  {
    id: 'e5',
    title: 'Movement & Stillness: Introduction to Bouldering',
    lane: 'growth',
    hostId: 'h4',
    description:
      'Bouldering is problem-solving at height. Caleb introduces newcomers to movement fundamentals — footwork, body position, reading a route — and explains why climbers talk about the wall as a kind of meditation.',
    location: 'Summit Collective, 47-22 11th St, Long Island City',
    dateTime: '2026-07-26T10:00:00',
    price: 75,
    spotsTotal: 10,
    spotsBooked: 6,
    imageSeed: '205',
    tags: ['Climbing', 'Physical', 'Beginner'],
  },
  {
    id: 'e6',
    title: 'Fermentation Fundamentals',
    lane: 'growth',
    hostId: 'h5',
    description:
      'Kimchi, kombucha, sourdough — fermentation is the oldest technology humans have. Nina walks you through the science and intuition of live cultures, and you\'ll go home with your own starter to keep alive.',
    location: 'Nina\'s Kitchen, 145 5th Ave, Park Slope',
    dateTime: '2026-08-09T13:00:00',
    price: 90,
    spotsTotal: 8,
    spotsBooked: 3,
    imageSeed: '206',
    tags: ['Cooking', 'Science', 'Food'],
  },
  {
    id: 'e7',
    title: 'On the Edge of the Universe: Rooftop Stargazing',
    lane: 'surprise',
    hostId: 'h6',
    description:
      'You already know the stars are there. You\'ve just forgotten to look. Eli Rosen brings telescopes and stories to a Williamsburg rooftop on a clear summer evening, turning the night sky into something that feels personal again.',
    location: 'The Wythe Hotel Rooftop, 80 Wythe Ave, Williamsburg',
    dateTime: '2026-07-21T20:30:00',
    price: 55,
    spotsTotal: 12,
    spotsBooked: 9,
    imageSeed: '207',
    tags: ['Astronomy', 'Outdoors', 'Wonder'],
  },
  {
    id: 'e8',
    title: 'Foraged & Found: A Hudson Valley Dinner',
    lane: 'surprise',
    hostId: 'h5',
    description:
      'Nina forages from dawn, then cooks in the afternoon, then feeds a table of strangers in the evening. The menu is a surprise — entirely dependent on what the day offered. Guests have described it as the best meal they\'ve had in years.',
    location: 'Nina\'s Kitchen, 145 5th Ave, Park Slope',
    dateTime: '2026-07-29T19:30:00',
    price: 145,
    spotsTotal: 8,
    spotsBooked: 7,
    imageSeed: '208',
    tags: ['Foraging', 'Dinner', 'Seasonal'],
  },
  {
    id: 'e9',
    title: 'The Blind Wine Tasting',
    lane: 'surprise',
    hostId: 'h2',
    description:
      'No labels. No clues. Just six glasses and your senses. James challenges you to identify grapes, regions, and vintages using only what you taste and smell. Humbling for experts, revelatory for beginners.',
    location: 'The Cork Room, 14 Bank St, West Village',
    dateTime: '2026-08-07T19:00:00',
    price: 110,
    spotsTotal: 10,
    spotsBooked: 4,
    imageSeed: '209',
    tags: ['Wine', 'Game', 'Tasting'],
  },
  {
    id: 'e10',
    title: 'Still Life Drawing Workshop',
    lane: 'passion',
    hostId: 'h3',
    description:
      'Suki trained at the Art Students League before philosophy claimed her. Once a month she runs a quiet drawing session for non-artists — no instruction, just observation, pencil, and time. "We talk too much. Drawing makes you slow down and really look."',
    location: 'Open Hearth Loft, 320 Atlantic Ave, Brooklyn',
    dateTime: '2026-08-03T15:00:00',
    price: 50,
    spotsTotal: 10,
    spotsBooked: 3,
    imageSeed: '210',
    tags: ['Drawing', 'Art', 'Quiet'],
  },
  {
    id: 'e11',
    title: 'Night Bouldering: The After-Dark Session',
    lane: 'surprise',
    hostId: 'h4',
    description:
      'The gym goes dark except for black lights. The routes glow. Music plays. Caleb leads a different kind of climbing session — playful, social, and a little unpredictable. For all levels.',
    location: 'Summit Collective, 47-22 11th St, Long Island City',
    dateTime: '2026-07-31T21:00:00',
    price: 60,
    spotsTotal: 20,
    spotsBooked: 11,
    imageSeed: '211',
    tags: ['Climbing', 'Night', 'Social'],
  },
  {
    id: 'e12',
    title: 'Philosophy of Technology: Are We Living Well?',
    lane: 'growth',
    hostId: 'h3',
    description:
      'A follow-up seminar to The Examined Life, focused on what we\'ve traded for convenience, connection, and constant notification. Suki structures this one as a debate: some defend the devices, others prosecute them.',
    location: 'Open Hearth Loft, 320 Atlantic Ave, Brooklyn',
    dateTime: '2026-08-14T18:30:00',
    price: 65,
    spotsTotal: 8,
    spotsBooked: 5,
    imageSeed: '212',
    tags: ['Philosophy', 'Technology', 'Ethics'],
  },
  {
    id: 'e13',
    title: 'Ramen from Scratch',
    lane: 'passion',
    hostId: 'h5',
    description:
      'A full day in Nina\'s kitchen learning tonkotsu broth, noodle making, and the choreography of a proper ramen bowl. Physically demanding, deeply satisfying. You\'ll eat what you make for lunch.',
    location: 'Nina\'s Kitchen, 145 5th Ave, Park Slope',
    dateTime: '2026-08-16T10:00:00',
    price: 135,
    spotsTotal: 6,
    spotsBooked: 4,
    imageSeed: '213',
    tags: ['Cooking', 'Japanese', 'Full Day'],
  },
  {
    id: 'e14',
    title: 'Planets & Mythology: A Guided Sky Tour',
    lane: 'growth',
    hostId: 'h6',
    description:
      'Eli traces the stories ancient cultures told to make sense of the same sky we see tonight. Part astronomy, part cultural history. You\'ll look at Orion differently afterward.',
    location: 'Rooftop at The Wythe, 80 Wythe Ave, Williamsburg',
    dateTime: '2026-08-22T20:00:00',
    price: 55,
    spotsTotal: 15,
    spotsBooked: 6,
    imageSeed: '214',
    tags: ['Astronomy', 'History', 'Storytelling'],
  },
  {
    id: 'e15',
    title: 'Urban Foraging Walk',
    lane: 'surprise',
    hostId: 'h5',
    description:
      'The city is edible — if you know what to look for. Nina leads a two-hour walk through Prospect Park identifying plants, mushrooms, and herbs. You\'ll leave with a small forage bag and serious second thoughts about what "weed" means.',
    location: 'Prospect Park, Grand Army Plaza entrance, Brooklyn',
    dateTime: '2026-07-27T09:00:00',
    price: 45,
    spotsTotal: 12,
    spotsBooked: 8,
    imageSeed: '215',
    tags: ['Foraging', 'Walking', 'Outdoors'],
  },
]

export const DEMO_USER: User = {
  id: 'u1',
  name: 'Alex Rivera',
  email: 'alex@example.com',
  bio: 'Curious by nature, often lost in a good book or a new neighborhood. Looking for more moments that feel real.',
  interests: ['Pottery', 'Philosophy', 'Cooking', 'Climbing'],
  walletBalanceCents: 15000,
  savedPaymentMethods: [
    {
      id: 'pm1',
      last4: '4242',
      brand: 'Visa',
      expiry: '09/27',
    },
  ],
}

export const DEMO_TRANSACTIONS: Transaction[] = [
  {
    id: 't1',
    userId: 'u1',
    type: 'topup',
    amountCents: 15000,
    description: 'Added funds',
    createdAt: '2026-07-01T10:00:00',
  },
]

export const DEMO_BOOKINGS: Booking[] = []

// ── Seed community users ──────────────────────────────────

export const SEED_USERS: SeedUser[] = [
  {
    id: 'su1',
    name: 'Nadia Chen',
    bio: 'Architect by day, potter on weekends. I believe slow things are the most interesting things.',
    interests: ['Pottery', 'Photography', 'Meditation', 'Film'],
    avatarSeed: '301',
    attendedExperienceIds: ['e1', 'e3', 'e10'],
  },
  {
    id: 'su2',
    name: 'Marcus Webb',
    bio: 'Former journalist. Now I just try to pay attention. Long walks, longer conversations.',
    interests: ['Philosophy', 'Hiking', 'Creative Writing', 'Film'],
    avatarSeed: '302',
    attendedExperienceIds: ['e4', 'e12', 'e7'],
  },
  {
    id: 'su3',
    name: 'Isabelle Torres',
    bio: 'Cook, forager, occasional insomniac. I moved to this city for the food and stayed for the people.',
    interests: ['Cooking', 'Foraging', 'Wine Tasting', 'Pottery'],
    avatarSeed: '303',
    attendedExperienceIds: ['e8', 'e15', 'e2', 'e13'],
  },
  {
    id: 'su4',
    name: 'Finn O\'Brien',
    bio: 'Climber, reader, overthinker. Trying to spend more time outside and less time online.',
    interests: ['Climbing', 'Hiking', 'Philosophy', 'Astronomy'],
    avatarSeed: '304',
    attendedExperienceIds: ['e5', 'e11', 'e14'],
  },
  {
    id: 'su5',
    name: 'Amara Osei',
    bio: "Pediatrician. I got into pottery after a particularly hard week and haven't stopped since.",
    interests: ['Pottery', 'Yoga', 'Meditation', 'Cooking'],
    avatarSeed: '305',
    attendedExperienceIds: ['e1', 'e6', 'e13'],
  },
  {
    id: 'su6',
    name: 'Soren Kvist',
    bio: 'Danish, displaced. Software by trade; astronomy, wine, and wandering by preference.',
    interests: ['Astronomy', 'Wine Tasting', 'Philosophy', 'Photography'],
    avatarSeed: '306',
    attendedExperienceIds: ['e7', 'e14', 'e9', 'e2'],
  },
  {
    id: 'su7',
    name: 'Laila Hassan',
    bio: 'PhD candidate in cultural anthropology. Fascinated by how people make meaning in cities.',
    interests: ['Philosophy', 'Creative Writing', 'Foraging', 'Dance'],
    avatarSeed: '307',
    attendedExperienceIds: ['e4', 'e15', 'e8'],
  },
  {
    id: 'su8',
    name: 'Rafael Mendez',
    bio: 'Musician, then chef, now somehow both. I believe every meal should have a soundtrack.',
    interests: ['Cooking', 'Live Music', 'Wine Tasting', 'Foraging'],
    avatarSeed: '308',
    attendedExperienceIds: ['e2', 'e13', 'e8', 'e6'],
  },
  {
    id: 'su9',
    name: 'Yuki Adachi',
    bio: 'Landscape designer. I spend my days thinking about how space shapes behavior.',
    interests: ['Hiking', 'Photography', 'Meditation', 'Astronomy'],
    avatarSeed: '309',
    attendedExperienceIds: ['e7', 'e15', 'e14'],
  },
  {
    id: 'su10',
    name: 'Cecile Dubois',
    bio: 'Originally from Lyon. Came for a fellowship, stayed for the curiosity. I write, mostly for myself.',
    interests: ['Creative Writing', 'Wine Tasting', 'Philosophy', 'Film'],
    avatarSeed: '310',
    attendedExperienceIds: ['e2', 'e9', 'e12', 'e4'],
  },
  {
    id: 'su11',
    name: 'Oliver Park',
    bio: 'Emergency medicine. I chase intensity at work; I come here for the opposite.',
    interests: ['Climbing', 'Woodworking', 'Meditation', 'Cooking'],
    avatarSeed: '311',
    attendedExperienceIds: ['e5', 'e11', 'e6', 'e3'],
  },
  {
    id: 'su12',
    name: 'Mei-Lin Zhang',
    bio: 'Urban planner. I believe cities should be lived in loudly, not just passed through.',
    interests: ['Foraging', 'Photography', 'Dance', 'Live Music'],
    avatarSeed: '312',
    attendedExperienceIds: ['e15', 'e8', 'e11'],
  },
]

// Experience → which seed users are attending (for guest list display)
export const EXPERIENCE_ATTENDEES: Record<string, string[]> = {
  e1:  ['su1', 'su5', 'su3'],
  e2:  ['su3', 'su6', 'su8', 'su10'],
  e3:  ['su1', 'su11'],
  e4:  ['su2', 'su7', 'su10'],
  e5:  ['su4', 'su11'],
  e6:  ['su5', 'su8', 'su11'],
  e7:  ['su6', 'su9', 'su2'],
  e8:  ['su3', 'su7', 'su8', 'su12'],
  e9:  ['su6', 'su10'],
  e10: ['su1'],
  e11: ['su4', 'su11', 'su12'],
  e12: ['su2', 'su10', 'su7'],
  e13: ['su3', 'su5', 'su8'],
  e14: ['su4', 'su6', 'su9'],
  e15: ['su3', 'su7', 'su9', 'su12'],
}

// Seed connections: demo user (u1) follows these people
export const SEED_CONNECTIONS: Connection[] = [
  { fromId: 'u1', toId: 'su1', createdAt: '2026-06-15T09:00:00' },
  { fromId: 'u1', toId: 'su2', createdAt: '2026-06-20T11:00:00' },
  { fromId: 'u1', toId: 'su4', createdAt: '2026-06-28T14:00:00' },
  { fromId: 'su1', toId: 'u1', createdAt: '2026-06-16T10:00:00' },
  { fromId: 'su2', toId: 'u1', createdAt: '2026-06-21T09:00:00' },
  { fromId: 'su3', toId: 'su1', createdAt: '2026-06-10T08:00:00' },
  { fromId: 'su6', toId: 'su2', createdAt: '2026-06-12T12:00:00' },
]

// ── Seed posts ────────────────────────────────────────────

export const SEED_POSTS: Post[] = [
  {
    id: 'p1',
    authorId: 'su1',
    experienceId: 'e1',
    content: 'Two hours with clay and I forgot entirely about my inbox. There is something about the resistance of the material — it doesn\'t care about your schedule. Marta said something I keep thinking about: "the pot tells you when it\'s ready, not the other way around."',
    createdAt: '2026-07-02T18:30:00',
    photo: 'https://picsum.photos/seed/pottery-entry-1/600/400',
    resonances: 14,
  },
  {
    id: 'p2',
    authorId: 'su2',
    experienceId: 'e4',
    content: 'Suki asked us: what do you actually believe, and how do you know? I said I believed in empirical evidence. She pushed back and I couldn\'t quite defend myself. Three days later I\'m still not sure I can. That\'s the mark of a good evening.',
    createdAt: '2026-07-04T21:00:00',
    resonances: 23,
  },
  {
    id: 'p3',
    authorId: 'su6',
    experienceId: 'e7',
    content: 'Eli pointed to a smudge of light above the horizon and told us it was a galaxy — 2.5 million light years away, older than anything I can imagine. I\'ve been staring at my ceiling since.',
    createdAt: '2026-07-05T23:15:00',
    photo: 'https://picsum.photos/seed/night-sky-entry/600/400',
    resonances: 31,
  },
  {
    id: 'p4',
    authorId: 'su3',
    experienceId: 'e8',
    content: 'We didn\'t know the menu until it arrived. The uncertainty was the point. Nina foraged at dawn and cooked all afternoon. I ate something called wood sorrel for the first time. It tasted like a lemon decided to become a leaf.',
    createdAt: '2026-06-30T22:00:00',
    photo: 'https://picsum.photos/seed/forage-table-entry/600/400',
    resonances: 18,
  },
  {
    id: 'p5',
    authorId: 'su4',
    experienceId: 'e5',
    content: 'Bouldering is the only sport where failure is just called "a project." You\'re not losing — you\'re working. I spent 40 minutes on one move and finally got it. The gym erupted. Strangers clapped. I cried a little. Don\'t tell anyone.',
    createdAt: '2026-07-06T20:00:00',
    resonances: 27,
  },
  {
    id: 'p6',
    authorId: 'su7',
    experienceId: 'e15',
    content: 'Walked two miles through Prospect Park and foraged enough for a small salad. Also learned I have been stepping over edible plants my entire life. The city has been hiding food in plain sight and I had no idea.',
    createdAt: '2026-07-03T16:45:00',
    resonances: 12,
  },
  {
    id: 'p7',
    authorId: 'su10',
    experienceId: 'e12',
    content: 'Suki\'s seminar on technology felt like being gently prosecuted. She didn\'t tell us what to think — she just kept asking "but why?" until we ran out of answers. I came in certain I had a healthy relationship with my phone. I left less sure.',
    createdAt: '2026-07-07T19:30:00',
    resonances: 9,
  },
  {
    id: 'p8',
    authorId: 'su8',
    experienceId: 'e13',
    content: 'Eight hours making ramen from scratch. My arms ache. My kitchen smells incredible. The broth took four hours alone. I understand now why a bowl of ramen at the right place can stop you mid-sentence.',
    createdAt: '2026-07-01T23:00:00',
    photo: 'https://picsum.photos/seed/ramen-craft-entry/600/400',
    resonances: 20,
  },
  {
    id: 'p9',
    authorId: 'su5',
    experienceId: null,
    content: 'I notice I\'ve stopped mindlessly scrolling since I started booking things here. Not because I\'m busier — I\'m not. But because I have something to look forward to that isn\'t on a screen. The anticipation alone changes the texture of a week.',
    createdAt: '2026-07-05T09:00:00',
    resonances: 44,
  },
  {
    id: 'p10',
    authorId: 'su9',
    experienceId: 'e14',
    content: 'Orion was a hunter. Before that, in older traditions, he was something else entirely. Eli showed us how the same cluster of stars had been reinterpreted across cultures for thousands of years. The sky is a mirror, not a map.',
    createdAt: '2026-07-06T22:30:00',
    resonances: 16,
  },
  {
    id: 'p11',
    authorId: 'su11',
    experienceId: 'e11',
    content: 'Night bouldering under black lights: the routes glow, the music is loud, and the routes that seemed impossible in daylight suddenly look different in purple. I sent three problems I\'d been stuck on for weeks. Something about the dark removes your self-consciousness.',
    createdAt: '2026-07-04T23:45:00',
    resonances: 22,
  },
  {
    id: 'p12',
    authorId: 'su12',
    experienceId: 'e15',
    content: 'Started the foraging walk as a skeptic. Ended it carrying dandelion greens and wood violets in a paper bag, genuinely excited. Nina moves through the park like she built it. She knows the name of every plant and most of the trees.',
    createdAt: '2026-07-03T17:30:00',
    resonances: 8,
  },
]
